### ISSUE TITLE
Simplify the CSS for the font-weight property.

### ISSUE THREAD

**Issue by josephtkim** [VSudowoodo/prj-rev-bwfs-dasmoto#5]
Great job simplifying the CSS code for the font-family property. You can simplify it further for the font-weight property as well.

```css
h1, h2, .price {
  font-weight: bold;
}
```
